[http]
port = 29002

[jwt_verify]
url = "http://10.100.11.246:29001/internal/jwt_verify_config"
header = "x-internal-token"
token = "dev-internal-token-change-me"

[storage]
user_key_salt = "please-change-to-random-long-string"

[s3]
provider = "s3"
endpoint = "http://127.0.0.1:9000"
public_bucket = "test-public-bucket"
private_bucket = "test-private-bucket"
region = "us-east-1"
access_key = "ROOTNAME"
secret_key = "CHANGEME123"

[r2]
provider = "cloudflare_r2"
endpoint = "https://<account_id>.r2.cloudflarestorage.com"
public_bucket = "app-public"
private_bucket = "app-private"
access_key = "<r2-access-key-id>"
secret_key = "<r2-secret-access-key>"
public_bucket_url = "https://assets.example.com"
